---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: deploy-beta
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_user
      password:
        from_secret: dockerhub_pass
      repo: rubasace/drone-java-bake-plugin
      tags: beta
    when:
      branch:
        - main
      event:
        - push

  - name: bake-release
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_user
      password:
        from_secret: dockerhub_pass
      repo: rubasace/drone-java-bake-plugin
      tags:
        - latest
        - ${CI_BUILD_TARGET}
    when:
      event:
        - promote

trigger:
  event:
    - push
    - promote
---
kind: signature
hmac: a5ba470f0243ea699cea77ffdd6aa51fb7fa7894fd7b6dc8b77d91ff02f390e6

...
