---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: bake-beta
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_user
      password:
        from_secret: dockerhub_pass
      repo: rubasace/drone-java-bake-plugin
      tags: beta
    when:
      branch:
        - main
trigger:
  event:
    - push
---
kind: signature
hmac: 8159dfad3b8c2f4869de28d36c1c9ee37d1f729a482e1c794d8d3dc2b1cfd428

...
