---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: deploy-beta
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_user
      password:
        from_secret: dockerhub_pass
      repo: rubasace/drone-java-bake-plugin
      tags: beta
    when:
      branch:
        - main
      event:
        - push

  - name: bake-release
    image: plugins/docker
    settings:
      username:
        from_secret: dockerhub_user
      password:
        from_secret: dockerhub_pass
      repo: rubasace/drone-java-bake-plugin
      tags:
        - latest
        - ${CI_BUILD_TARGET}
    when:
      event:
        - promote

  - name: tag-release
    image: docker:git
    commands:
      - git add .
      - git commit --allow-empty -m "Release ${CI_BUILD_TARGET}"
      - git tag ${CI_BUILD_TARGET}
      - git push origin ${CI_BUILD_TARGET}
    when:
      event:
        - promote

trigger:
  event:
    - push
    - promote
---
kind: signature
hmac: 11ce925334b67d129e7a3158839c1e483f5cff0e7f9322c32322cc4aa80f185c

...
